###
POST http://localhost:8080/user  HTTP/1.1
content-type: application/json

{
    "username": "usuario",
    "password": "password",
    "email": "admin@admin.com"
}

###
POST http://localhost:8080/auth/login HTTP/1.1
content-type: application/json

{
    "username": "usuario",
    "password": "password"
}

###
POST http://localhost:8080/api/tipocambio HTTP/1.1
content-type: application/json
Authorization: token eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJzb2Z0dGVrSldUIiwic3ViIjoidXN1YXJpbyIsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3Nzk4OTcwMDUsImV4cCI6MTc3OTg5NzYwNX0.S0e4H7iobzMUpV0CWgnP_lA6WGiIE-dVsl2B_k1tu-bSgsKzyDDYv1ACjnib1swTDFvjcVsiLncLOPXvH_lNZQ

{
    "montoOrigen": 50.0,
    "monedaOrigen": "USD",
    "monedaDestino": "EUR"
}

###
GET http://localhost:8080/api/tipocambios?limit=5&page=0 HTTP/1.1
content-type: application/json
Authorization: token eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJzb2Z0dGVrSldUIiwic3ViIjoidXN1YXJpbyIsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3Nzk4OTcwMDUsImV4cCI6MTc3OTg5NzYwNX0.S0e4H7iobzMUpV0CWgnP_lA6WGiIE-dVsl2B_k1tu-bSgsKzyDDYv1ACjnib1swTDFvjcVsiLncLOPXvH_lNZQ