DROP TABLE IF EXISTS TIPOCAMBIO;
  
CREATE TABLE TIPOCAMBIO (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  MONEDA_ORIGEN CHAR(3) NOT NULL,
  MONEDA_DESTINO CHAR(3) NOT NULL,
  FACTOR_TIPO_CAMBIO DECIMAL DEFAULT 1.0
);